spring:
  redis:
    host: localhost
    port: 6379
  jpa:
    show-sql: false
  application:
    name: Content-Management
  datasource:
    url: jdbc:mysql://localhost:3306/CONTENTMGMT
    username: root
    password: ticketmaster
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9003
  servlet:
    context-path: /content
logging:
  path: /Users/family/Desktop/IMP/Project/logs
  level:
    root: INFO
jwt:
  secretKey: asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7y
