spring:
  jpa:
    show-sql: true
  application:
    name: Content-Management
  datasource:
    url: jdbc:mysql://localhost:3306/CONTENTMGMT
    username: root
    password: ticketmaster
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9003
logging:
  path: /Users/family/Desktop/IMP/Project/logs
  level:
    root: INFO